"use client";
import {useEffect,useState} from "react";
import {householdApi,HouseholdMember,HouseholdState} from "./supabase";

export type Identity = HouseholdMember & { householdId: string; householdName: string };
const IDENTITY_KEY="motions-identity";
export const loadIdentity=():Identity|null=>{try{return JSON.parse(localStorage.getItem(IDENTITY_KEY)||"null")}catch{return null}};

export default function HouseholdGate({children}:{children:(identity:Identity,switchPerson:()=>void)=>React.ReactNode}){
 const[loading,setLoading]=useState(true),[house,setHouse]=useState<HouseholdState|null>(null),[identity,setIdentity]=useState<Identity|null>(null),[mode,setMode]=useState<"welcome"|"create"|"join"|"choose"|"pin">("welcome"),[selected,setSelected]=useState<HouseholdMember|null>(null),[error,setError]=useState(""),[joinCode,setJoinCode]=useState(""),[andrewPin,setAndrewPin]=useState(""),[abbyPin,setAbbyPin]=useState(""),[pin,setPin]=useState(""),[newCode,setNewCode]=useState("");
 useEffect(()=>{(async()=>{try{const h=await householdApi.mine();setHouse(h);const local=loadIdentity(),remembered=h?.members.find(m=>m.id===h.remembered_member_id),member=remembered||h?.members.find(m=>m.id===local?.id);if(h&&member){const id={...member,householdId:h.household_id,householdName:h.household_name};localStorage.setItem(IDENTITY_KEY,JSON.stringify(id));setIdentity(id)}else if(h)setMode("choose")}catch(e){setError(e instanceof Error?e.message:"Could not connect") }finally{setLoading(false)}})()},[]);
 async function create(){if(!/^\d{4}$/.test(andrewPin)||!/^\d{4}$/.test(abbyPin)){setError("Both PINs must contain four numbers.");return}setLoading(true);setError("");try{const x=await householdApi.create(andrewPin,abbyPin);setHouse(x.household);setNewCode(x.join_code);setMode("choose")}catch(e){setError(e instanceof Error?e.message:"Could not create household")}finally{setLoading(false)}}
 async function join(){setLoading(true);setError("");try{const h=await householdApi.join(joinCode);setHouse(h);setMode("choose")}catch(e){setError(e instanceof Error?e.message:"That setup code was not recognized.")}finally{setLoading(false)}}
 async function unlock(){if(!selected||!house)return;setLoading(true);setError("");try{if(!await householdApi.remember(selected.id,pin)){setError("That PIN doesn’t match.");return}const id={...selected,householdId:house.household_id,householdName:house.household_name};localStorage.setItem(IDENTITY_KEY,JSON.stringify(id));setIdentity(id);setPin("")}catch(e){setError(e instanceof Error?e.message:"Could not verify PIN")}finally{setLoading(false)}}
 function choose(m:HouseholdMember){setSelected(m);setPin("");setError("");setMode("pin")}
 if(identity)return <>{children(identity,()=>{setIdentity(null);setMode("choose")})}</>;
 return <main className="gate"><div className="gate-glow"/><section className="gate-card"><p className="gate-brand">MOTIONS</p>{loading?<><div className="gate-mark">M</div><h1>Opening your household…</h1></>:mode==="welcome"?<><p className="kicker">SHARED MEMORY</p><h1>Move through<br/>the day together.</h1><p className="gate-copy">Create your household on the first phone. Use the private setup code to connect the second.</p><button className="gate-primary" onClick={()=>setMode("create")}>CREATE OUR HOUSEHOLD</button><button className="gate-secondary" onClick={()=>setMode("join")}>JOIN WITH A SETUP CODE</button></>:mode==="create"?<><button className="gate-back" onClick={()=>setMode("welcome")}>←</button><p className="kicker">FIRST-TIME SETUP</p><h1>Create your<br/>household.</h1><label>ANDREW’S 4-DIGIT PIN<input inputMode="numeric" maxLength={4} value={andrewPin} onChange={e=>setAndrewPin(e.target.value.replace(/\D/g,""))} type="password"/></label><label>ABBY’S 4-DIGIT PIN<input inputMode="numeric" maxLength={4} value={abbyPin} onChange={e=>setAbbyPin(e.target.value.replace(/\D/g,""))} type="password"/></label><button className="gate-primary" onClick={create}>CREATE HOUSEHOLD</button></>:mode==="join"?<><button className="gate-back" onClick={()=>setMode("welcome")}>←</button><p className="kicker">SECOND DEVICE</p><h1>Join your<br/>household.</h1><label>HOUSEHOLD SETUP CODE<input className="code-input" autoCapitalize="characters" value={joinCode} onChange={e=>setJoinCode(e.target.value)} placeholder="AB12-CD34"/></label><button className="gate-primary" onClick={join}>CONNECT THIS DEVICE</button></>:mode==="choose"?<><p className="kicker">WHO’S MOVING TODAY?</p><h1>Choose your<br/>profile.</h1>{newCode&&<div className="setup-code"><small>SECOND-PHONE SETUP CODE</small><strong>{newCode}</strong><span>Save this privately. It is shown only now.</span></div>}<div className="profile-choice">{house?.members.map(m=><button key={m.id} onClick={()=>choose(m)}><i className={m.name==="Andrew"?"a":"b"}>{m.name[0]}</i><b>{m.name}</b>{m.is_admin&&<small>ADMINISTRATOR</small>}</button>)}</div></>:<><button className="gate-back" onClick={()=>setMode("choose")}>←</button><p className="kicker">WELCOME, {selected?.name.toUpperCase()}</p><h1>Enter your PIN.</h1><div className="pin-dots">{[0,1,2,3].map(i=><i key={i} className={pin.length>i?"on":""}/>)}</div><input aria-label="Four digit PIN" className="pin-hidden" autoFocus inputMode="numeric" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} type="password"/><button className="gate-primary" disabled={pin.length!==4} onClick={unlock}>ENTER MOTIONS</button></>}{error&&<p className="gate-error">{error}</p>}</section></main>
}
