"use client";
import {useEffect,useState} from "react";
import HouseholdGate,{Identity} from "./HouseholdGate";
type M={id:string;title:string;label:string;time:string;image:string;accent:string;message:string;tasks:string[]};
const M:M[]=[
{id:"morning",title:"Before 7am",label:"Morning launch",time:"Before 7:00",accent:"#d6a443",image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85",message:"Morning is moving.",tasks:["Wake up","Music ready","Play music","Things picked up for kids","Get dressed","Devotions","Eat something","Get outside as quickly as possible"]},
{id:"church",title:"Leaving for Church",label:"Sunday departure",time:"Sunday · 9:30",accent:"#7b4b45",image:"https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&w=1200&q=85",message:"You’re ready to go.",tasks:["Make sure we have Bibles","Church attire accessories — tie, clip, shoes, bows","Hair done","Teeth brushed","Mints accessible","Supplies verified","Video ready","Van tidy","Diaper bag","Change of clothes","Energy","Pen","Prayer cards","Devices charged","Pacis","Room key","Message prepped","Route mapped","Suit coat"]},
{id:"onway",title:"On the Way to Church",label:"Road rhythm",time:"In transit",accent:"#677457",image:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85",message:"Arrive ready.",tasks:["Route mapped","Message audio ready","Water accessible","Pray together","Arrival plan checked"]},
{id:"leaving",title:"Leaving Church",label:"Departure sweep",time:"After service",accent:"#365d62",image:"https://images.unsplash.com/photo-1444492417251-9c84a5fa18e0?auto=format&fit=crop&w=1200&q=85",message:"Nothing left behind.",tasks:["Devices","Bibles","Table supplies","Video USB","Check","Diapers","Suit coat"]},
{id:"dinner",title:"Dinner",label:"Evening reset",time:"Tonight",accent:"#c98258",image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85",message:"Dinner is closed.",tasks:["Clear plates and silverware","Napkins put in laundry","Dishes washed","Leftovers put away","Trash taken out","Floor swept","Table wiped down","Counters cleared of debris"]},
{id:"bed",title:"Before Bed",label:"Night shutdown",time:"10:00 PM",accent:"#907865",image:"https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=85",message:"The house is down for the night.",tasks:["Living room picked up","Brush teeth","Wash face","Set out clothes for next day","Ironing board out of bedroom before baby","Next day game day","Devices plugged in","Lights off","Clean laundry all folded","Dirty laundry in hamper or machine","Debris organized"]}];
const daily=["Exercise","Prayer for missionaries","Bible story prep","Bible story","Reading to kids","Watching a kids show","Drink water"];
const weekly=["Sermons uploaded","Relay log","Thank you notes","Charge watch","Polarsteps","Rocket Money / mortgage","Change in change pouch","Clean kids’ car seats","Diapers out of car"];
const buzz=(big=false)=>{if("vibrate" in navigator)navigator.vibrate(big?[25,25,45]:10)};
function MotionsApp({identity,switchPerson}:{identity:Identity;switchPerson:()=>void}){const[tab,setTab]=useState("today"),[card,setCard]=useState(0),[open,setOpen]=useState<M|null>(null),[focus,setFocus]=useState(false),[done,setDone]=useState<Record<string,string[]>>({}),[habits,setHabits]=useState<string[]>([]),[complete,setComplete]=useState(false),[touch,setTouch]=useState(0);
useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("motions")||"{}");setDone(x.done||{});setHabits(x.habits||[])}catch{}},[]);useEffect(()=>{if(Object.keys(done).length||habits.length)localStorage.setItem("motions",JSON.stringify({done,habits}))},[done,habits]);
const checked=open?done[open.id]||[]:[],next=open?.tasks.find(x=>!checked.includes(x));function toggle(m:M,t:string){const was=(done[m.id]||[]).includes(t),n=was?(done[m.id]||[]).filter(x=>x!==t):[...(done[m.id]||[]),t];setDone({...done,[m.id]:n});buzz(n.length===m.tasks.length);if(!was&&n.length===m.tasks.length)setTimeout(()=>setComplete(true),250)}function enter(m:M){setOpen(m);setComplete(false);setFocus(false);buzz()}
if(open)return <main className="motion" style={{"--photo":`url(${open.image})`,"--accent":open.accent} as React.CSSProperties}><div className="photo"/><div className="shade"/>{complete?<section className="complete"><i>✓</i><small>MOTION COMPLETE</small><h1>{open.message}</h1><p>Everything important has been carried forward.</p><button onClick={()=>setOpen(null)}>RETURN TO TODAY <b>→</b></button><a onClick={()=>{setDone({...done,[open.id]:[]});setComplete(false)}}>Reset this Motion</a></section>:focus?<section className="focus"><header><button onClick={()=>setFocus(false)}>×</button><b>{open.title}</b><button>•••</button></header><div className="dots">{open.tasks.map(t=><i key={t} className={checked.includes(t)?"on":""}/>)}</div>{next&&<><em>{String(open.tasks.indexOf(next)+1).padStart(2,"0")}</em><small>UP NEXT</small><h1>{next}</h1><p>{checked.length} OF {open.tasks.length} COMPLETE</p><button className="gold" onClick={()=>toggle(open,next)}>✓ &nbsp; DONE</button><a>SKIP →</a></>}</section>:<section className="list"><header><button onClick={()=>setOpen(null)}>×</button><button>•••</button></header><div className="title"><small>{open.label}</small><h1>{open.title}</h1><p><span>{checked.length} OF {open.tasks.length} COMPLETE</span><span>{Math.round(checked.length/open.tasks.length*100)}%</span></p><i><b style={{width:`${checked.length/open.tasks.length*100}%`}}/></i></div><div className="tasks">{open.tasks.map((t,i)=><button key={t} className={checked.includes(t)?"done":""} onClick={()=>toggle(open,t)}><i>{checked.includes(t)?"✓":""}</i><span>{t}</span><small>{String(i+1).padStart(2,"0")}</small></button>)}</div><button className="focusbtn" onClick={()=>setFocus(true)}>◎ &nbsp; ONE AT A TIME</button></section>}</main>;
return <main className="app">{tab==="today"&&<section className="screen today"><header><div><small>{new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric"}).format(new Date()).toUpperCase()}</small><h1>MOTIONS</h1></div><button onClick={()=>setTab("house")}>{identity.name[0]}</button></header><div className="intro"><p>Your day, in order.</p><span>{M.filter(m=>(done[m.id]||[]).length===m.tasks.length).length}/{M.length} CLOSED</span></div><div className="deck" onTouchStart={e=>setTouch(e.touches[0].clientX)} onTouchEnd={e=>{let d=e.changedTouches[0].clientX-touch;if(Math.abs(d)>40){setCard((card+(d<0?1:-1)+M.length)%M.length);buzz()}}}><div className="back b3" style={{background:M[(card+3)%M.length].accent}}/><div className="back b2" style={{background:M[(card+2)%M.length].accent}}/><div className="back b1" style={{background:M[(card+1)%M.length].accent}}/><article style={{"--photo":`url(${M[card].image})`,"--accent":M[card].accent} as React.CSSProperties} onClick={()=>enter(M[card])}><div className="cover"/><div className="fade"/><div className="top"><span>{card===0?"NEXT UP":"LATER"}</span><span>{M[card].time}</span></div><div className="copy"><small>{M[card].label}</small><h2>{M[card].title}</h2><p>{(done[M[card].id]||[]).length} OF {M[card].tasks.length} DONE <i><b style={{width:`${(done[M[card].id]||[]).length/M[card].tasks.length*100}%`}}/></i></p><button>OPEN MOTION <b>↗</b></button></div></article></div><div className="controls"><button onClick={()=>setCard((card-1+M.length)%M.length)}>←</button><span>{M.map((_,i)=><i className={i===card?"on":""} key={i}/>)}</span><button onClick={()=>setCard((card+1)%M.length)}>→</button></div><label>SWIPE THROUGH YOUR DAY</label></section>}
{tab==="motions"&&<section className="screen library"><Page title="All Motions" label="YOUR REPEATABLE LIFE"/><div className="grid">{M.map((m,i)=><button key={m.id} onClick={()=>enter(m)} style={{"--photo":`url(${m.image})`} as React.CSSProperties}><span className="pic"/><span className="fade"/><em>0{i+1}</em><div><small>{m.label}</small><b>{m.title}</b><label>{m.tasks.length} STEPS · {m.time}</label></div></button>)}</div></section>}
{tab==="rhythms"&&<section className="screen rhythms"><Page title="Rhythms" label="KEEP THE BEAT"/><h2>The habits that keep<br/>our days strong.</h2><h3>DAILY RHYTHMS</h3><div className="habitgrid">{daily.map((x,i)=><button key={x} className={habits.includes(x)?"done":""} onClick={()=>{setHabits(habits.includes(x)?habits.filter(h=>h!==x):[...habits,x]);buzz()}}><i>{habits.includes(x)?"✓":["↟","✦","◫","⌁","◌","◉","≈"][i]}</i><b>{x}</b><small>{habits.includes(x)?"DONE":"TAP TO MARK"}</small></button>)}</div><h3>THIS WEEK</h3><div className="week">{weekly.map(x=><button key={x} className={habits.includes(x)?"done":""} onClick={()=>{setHabits(habits.includes(x)?habits.filter(h=>h!==x):[...habits,x]);buzz()}}><i>{habits.includes(x)?"✓":"○"}</i><span>{x}</span><small>WEEKLY</small></button>)}</div></section>}
{tab==="house"&&<section className="screen house"><Page title="Household" label="SHARED MEMORY" plain/><h2>We’re in this<br/>together.</h2><div className="people profile-people"><button className={identity.name==="Andrew"?"current":""} onClick={identity.name==="Andrew"?undefined:switchPerson}><i className="a">A</i><b>Andrew</b><small>{identity.name==="Andrew"?"THIS DEVICE":"SWITCH PROFILE"}</small></button><button className={identity.name==="Abby"?"current":""} onClick={identity.name==="Abby"?undefined:switchPerson}><i className="b">A</i><b>Abby</b><small>{identity.name==="Abby"?"THIS DEVICE":"SWITCH PROFILE"}</small></button></div><div className="pulse"><small>HOUSEHOLD PULSE</small><b>{Object.values(done).flat().length+habits.length}</b><span>small things carried together today</span></div><h3>TODAY’S ACTIVITY</h3><div className="activity empty-activity"><p>Activity will appear here as Andrew and Abby complete real tasks.</p></div><button className="switch-profile" onClick={switchPerson}>SWITCH PERSON</button></section>}
<nav>{[["today","☼","Today"],["motions","▱","Motions"],["rhythms","≈","Rhythms"],["house","♧","Household"]].map(x=><button key={x[0]} className={tab===x[0]?"on":""} onClick={()=>{setTab(x[0]);buzz()}}><i>{x[1]}</i><span>{x[2]}</span></button>)}</nav></main>}
function Page({title,label,plain=false}:{title:string,label:string;plain?:boolean}){return <header className="page"><div><small>{label}</small><h1>{title}</h1></div>{!plain&&<button>＋</button>}</header>}
export default function Home(){return <HouseholdGate>{(identity,switchPerson)=><MotionsApp identity={identity} switchPerson={switchPerson}/>}</HouseholdGate>}
