"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import HouseholdGate, { Identity } from "./HouseholdGate";
import { householdApi, ProgressRow, RhythmRecurrence, SharedMotion, SharedRhythm } from "./supabase";

type Motion = SharedMotion;

const defaults: Motion[] = [
  {id:"morning",title:"Before 7am",label:"Morning launch",time:"Before 7:00",accent:"#d6a443",image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85",message:"Morning is moving.",tasks:["Wake up","Music ready","Play music","Things picked up for kids","Get dressed","Devotions","Eat something","Get outside as quickly as possible"]},
  {id:"church",title:"Leaving for Church",label:"Sunday departure",time:"Sunday · 9:30",accent:"#7b4b45",image:"https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&w=1200&q=85",message:"You’re ready to go.",tasks:["Make sure we have Bibles","Church attire accessories — tie, clip, shoes, bows","Hair done","Teeth brushed","Mints accessible","Supplies verified","Video ready","Van tidy","Diaper bag","Change of clothes","Energy","Pen","Prayer cards","Devices charged","Pacis","Room key","Message prepped","Route mapped","Suit coat"]},
  {id:"onway",title:"On the Way to Church",label:"Road rhythm",time:"In transit",accent:"#677457",image:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85",message:"Arrive ready.",tasks:["Route mapped","Message audio ready","Water accessible","Pray together","Arrival plan checked"]},
  {id:"leaving",title:"Leaving Church",label:"Departure sweep",time:"After service",accent:"#365d62",image:"https://images.unsplash.com/photo-1444492417251-9c84a5fa18e0?auto=format&fit=crop&w=1200&q=85",message:"Nothing left behind.",tasks:["Devices","Bibles","Table supplies","Video USB","Check","Diapers","Suit coat"]},
  {id:"dinner",title:"Dinner",label:"Evening reset",time:"Tonight",accent:"#c98258",image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85",message:"Dinner is closed.",tasks:["Clear plates and silverware","Napkins put in laundry","Dishes washed","Leftovers put away","Trash taken out","Floor swept","Table wiped down","Counters cleared of debris"]},
  {id:"bed",title:"Before Bed",label:"Night shutdown",time:"10:00 PM",accent:"#907865",image:"https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=85",message:"The house is down for the night.",tasks:["Living room picked up","Brush teeth","Wash face","Set out clothes for next day","Ironing board out of bedroom before baby","Next day game day","Devices plugged in","Lights off","Clean laundry all folded","Dirty laundry in hamper or machine","Debris organized"]}
];

const daily=["Exercise","Prayer for missionaries","Bible story prep","Bible story","Reading to kids","Watching a kids show","Drink water"];
const weekly=["Sermons uploaded","Relay log","Thank you notes","Charge watch","Polarsteps","Rocket Money / mortgage","Change in change pouch","Clean kids’ car seats","Diapers out of car"];
const buzz=(big=false)=>{if(typeof navigator!=="undefined"&&"vibrate" in navigator)navigator.vibrate(big?[25,25,45]:10)};
const dateKey=()=>{const d=new Date(),p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const weekKey=()=>{const d=new Date(),day=(d.getDay()+6)%7,p=(n:number)=>String(n).padStart(2,"0");d.setDate(d.getDate()-day);return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const monthKey=()=>dateKey().slice(0,7);
const rhythmPeriod=(r:SharedRhythm)=>r.recurrence==="daily"?`rhythm-day:${dateKey()}`:r.recurrence==="weekly"?`rhythm-week:${weekKey()}`:r.recurrence==="monthly"?`rhythm-month:${monthKey()}`:`rhythm-custom:${r.id}:${Math.max(0,Math.floor((new Date(dateKey()+"T12:00:00").getTime()-new Date(r.startDate+"T12:00:00").getTime())/86400000/Math.max(1,r.intervalDays)))}`;
const rhythmSchedule=(r:SharedRhythm)=>r.recurrence==="daily"?"DAILY":r.recurrence==="weekly"?`WEEKLY · ${r.days.length?r.days.map(d=>["SUN","MON","TUE","WED","THU","FRI","SAT"][d]).join(" · "):"ANY DAY"}`:r.recurrence==="monthly"?`MONTHLY · DAY ${r.dayOfMonth}`:`EVERY ${r.intervalDays} DAYS`;
const rhythmDefaults:SharedRhythm[]=[...daily.map((title,i)=>({id:`daily-${i}`,title,category:"Personal",assignee:"Everyone" as const,recurrence:"daily" as const,days:[],dayOfMonth:1,intervalDays:2,startDate:dateKey()})),...weekly.map((title,i)=>({id:`weekly-${i}`,title,category:"Household",assignee:"Everyone" as const,recurrence:"weekly" as const,days:[1],dayOfMonth:1,intervalDays:7,startDate:dateKey()}))];
const copyMotions=(items:Motion[])=>items.map(m=>({...m,tasks:[...m.tasks]}));

function MotionEditor({motion,onCancel,onSave}:{motion:Motion|null;onCancel:()=>void;onSave:(motion:Motion)=>void}){
  const [draft,setDraft]=useState<Motion>(()=>motion?{...motion,tasks:[...motion.tasks]}:{id:`motion-${Date.now()}`,title:"",label:"",time:"",image:"",accent:"#d6a443",message:"Motion complete.",tasks:[""]});
  const field=(key:keyof Motion,value:string)=>setDraft({...draft,[key]:value});
  const updateTask=(index:number,value:string)=>{const tasks=[...draft.tasks];tasks[index]=value;setDraft({...draft,tasks})};
  const addTask=()=>setDraft({...draft,tasks:[...draft.tasks,""]});
  const moveTask=(index:number,change:number)=>{const destination=index+change;if(destination<0||destination>=draft.tasks.length)return;const tasks=[...draft.tasks];[tasks[index],tasks[destination]]=[tasks[destination],tasks[index]];setDraft({...draft,tasks})};
  const removeTask=(index:number)=>{const tasks=draft.tasks.filter((_,taskIndex)=>taskIndex!==index);setDraft({...draft,tasks:tasks.length?tasks:[""]})};
  return <div className="editor-backdrop"><form className="motion-editor" onSubmit={e=>{e.preventDefault();const tasks=draft.tasks.map(task=>task.trim()).filter(Boolean);if(!draft.title.trim()||!tasks.length)return;onSave({...draft,title:draft.title.trim(),tasks})}}>
    <header><div><small>{motion?"UPDATE MOTION":"NEW MOTION"}</small><h2>{motion?"Edit Motion":"Create Motion"}</h2></div><button type="button" onClick={onCancel}>×</button></header>
    <label>Title<input value={draft.title} onChange={e=>field("title",e.target.value)} placeholder="Before 7am" required/></label>
    <div className="editor-row"><label>Small label<input value={draft.label} onChange={e=>field("label",e.target.value)} placeholder="Morning launch"/></label><label>Time<input value={draft.time} onChange={e=>field("time",e.target.value)} placeholder="Before 7:00"/></label></div>
    <label>Photo URL<input value={draft.image} onChange={e=>field("image",e.target.value)} placeholder="https://…"/></label>
    <div className="editor-row"><label>Accent color<input type="color" value={draft.accent} onChange={e=>field("accent",e.target.value)}/></label><label>Completion message<input value={draft.message} onChange={e=>field("message",e.target.value)}/></label></div>
    <label>Steps</label>
    <div className="step-editor">{draft.tasks.map((task,index)=><div className="step-row" key={index}><span className="step-number">{index+1}</span><input value={task} onChange={e=>updateTask(index,e.target.value)} placeholder={`Step ${index+1}`} aria-label={`Step ${index+1}`} required={draft.tasks.length===1}/><div className="step-actions"><button type="button" onClick={()=>moveTask(index,-1)} disabled={index===0}>UP</button><button type="button" onClick={()=>moveTask(index,1)} disabled={index===draft.tasks.length-1}>DOWN</button><button type="button" className="remove-step" onClick={()=>removeTask(index)}>REMOVE</button></div></div>)}</div>
    <button type="button" className="add-step" onClick={addTask}>+ ADD STEP</button>
    <footer className="editor-actions"><button type="button" onClick={onCancel}>CANCEL</button><button className="save" type="submit">SAVE MOTION</button></footer>
  </form></div>;
}

function MotionActions({index,total,onClose,onEdit,onDuplicate,onMove,onDelete}:{index:number;total:number;onClose:()=>void;onEdit:()=>void;onDuplicate:()=>void;onMove:(n:number)=>void;onDelete:()=>void}){
  return <div className="actions-backdrop" onClick={onClose}><div className="motion-actions" onClick={e=>e.stopPropagation()}><b>MANAGE MOTION</b><button onClick={onEdit}>Edit motion</button><button onClick={onDuplicate}>Duplicate motion</button><button disabled={index===0} onClick={()=>onMove(-1)}>Move earlier</button><button disabled={index===total-1} onClick={()=>onMove(1)}>Move later</button><button className="danger" onClick={onDelete}>Delete motion</button><button onClick={onClose}>Cancel</button></div></div>;
}

function RhythmEditor({rhythm,onCancel,onSave}:{rhythm:SharedRhythm|null;onCancel:()=>void;onSave:(rhythm:SharedRhythm)=>void}){
  const [draft,setDraft]=useState<SharedRhythm>(()=>rhythm?{...rhythm,days:[...rhythm.days]}:{id:`rhythm-${Date.now()}`,title:"",category:"Household",assignee:"Everyone",recurrence:"daily",days:[1],dayOfMonth:1,intervalDays:2,startDate:dateKey()});
  const recurrence=(value:RhythmRecurrence)=>setDraft({...draft,recurrence:value});
  return <div className="editor-backdrop"><form className="motion-editor rhythm-editor" onSubmit={e=>{e.preventDefault();if(draft.title.trim())onSave({...draft,title:draft.title.trim(),category:draft.category.trim()||"Household"})}}>
    <header><div><small>{rhythm?"UPDATE RHYTHM":"NEW RHYTHM"}</small><h2>{rhythm?"Edit Rhythm":"Create Rhythm"}</h2></div><button type="button" onClick={onCancel}>×</button></header>
    <label>Name<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Drink water" required/></label>
    <div className="editor-row"><label>Category<input value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})} placeholder="Household"/></label><label>Assigned to<select value={draft.assignee} onChange={e=>setDraft({...draft,assignee:e.target.value as SharedRhythm["assignee"]})}><option>Everyone</option><option>Andrew</option><option>Abby</option></select></label></div>
    <label>Repeats<select value={draft.recurrence} onChange={e=>recurrence(e.target.value as RhythmRecurrence)}><option value="daily">Every day</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="custom">Custom interval</option></select></label>
    {draft.recurrence==="weekly"&&<fieldset><legend>Days of the week</legend><div className="day-picker">{["S","M","T","W","T","F","S"].map((label,day)=><button type="button" className={draft.days.includes(day)?"on":""} key={day} onClick={()=>setDraft({...draft,days:draft.days.includes(day)?draft.days.filter(d=>d!==day):[...draft.days,day].sort()})}>{label}</button>)}</div></fieldset>}
    {draft.recurrence==="monthly"&&<label>Day of month<input type="number" min="1" max="31" value={draft.dayOfMonth} onChange={e=>setDraft({...draft,dayOfMonth:Number(e.target.value)})}/></label>}
    {draft.recurrence==="custom"&&<div className="editor-row"><label>Every how many days<input type="number" min="1" value={draft.intervalDays} onChange={e=>setDraft({...draft,intervalDays:Number(e.target.value)})}/></label><label>Starting<input type="date" value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/></label></div>}
    <footer className="editor-actions"><button type="button" onClick={onCancel}>CANCEL</button><button className="save" type="submit">SAVE RHYTHM</button></footer>
  </form></div>;
}

function RhythmActions({index,total,onClose,onEdit,onMove,onDelete}:{index:number;total:number;onClose:()=>void;onEdit:()=>void;onMove:(n:number)=>void;onDelete:()=>void}){
  return <div className="actions-backdrop" onClick={onClose}><div className="motion-actions" onClick={e=>e.stopPropagation()}><b>MANAGE RHYTHM</b><button onClick={onEdit}>Edit rhythm</button><button disabled={index===0} onClick={()=>onMove(-1)}>Move earlier</button><button disabled={index===total-1} onClick={()=>onMove(1)}>Move later</button><button className="danger" onClick={onDelete}>Delete rhythm</button><button onClick={onClose}>Cancel</button></div></div>;
}

function MotionsApp({identity,switchPerson}:{identity:Identity;switchPerson:()=>void}){
  const [tab,setTab]=useState("today"),[card,setCard]=useState(0),[cardMotion,setCardMotion]=useState<"next"|"prev">("next"),[openId,setOpenId]=useState<string|null>(null),[focus,setFocus]=useState(false),[done,setDone]=useState<Record<string,string[]>>({}),[habits,setHabits]=useState<string[]>([]),[activity,setActivity]=useState<ProgressRow[]>([]),[complete,setComplete]=useState(false),[touch,setTouch]=useState(0);
  const swiped=useRef(false);
  const [motions,setMotions]=useState<Motion[]>(defaults),[editor,setEditor]=useState<Motion|null|undefined>(undefined),[menuId,setMenuId]=useState<string|null>(null),[saving,setSaving]=useState(false);
  const [rhythms,setRhythms]=useState<SharedRhythm[]>(rhythmDefaults),[rhythmEditor,setRhythmEditor]=useState<SharedRhythm|null|undefined>(undefined),[rhythmMenuId,setRhythmMenuId]=useState<string|null>(null);
  const day=`day:${dateKey()}`,week=`week:${weekKey()}`;
  const rhythmPeriods=useMemo(()=>Array.from(new Set(rhythms.map(rhythmPeriod))),[rhythms]);
  const open=useMemo(()=>motions.find(m=>m.id===openId)||null,[motions,openId]);

  function applyProgress(rows:ProgressRow[]){const nextDone:Record<string,string[]>={},nextHabits:string[]=[];rows.filter(r=>r.completed).forEach(r=>{if(r.item_type==="motion"){const [id,index]=r.item_id.split(":");const task=motions.find(m=>m.id===id)?.tasks[Number(index)];if(task)(nextDone[id]||=[]).push(task)}else if(r.item_type==="rhythm")nextHabits.push(r.item_id)});setDone(nextDone);setHabits(nextHabits);setActivity(rows.filter(r=>r.completed).slice(0,12))}
  async function refresh(){try{applyProgress(await householdApi.progress([day,...rhythmPeriods]))}catch{}}
  async function refreshMotions(){try{const remote=await householdApi.motions();if(remote.length){setMotions(remote);localStorage.setItem("motions-library",JSON.stringify(remote))}}catch{}}
  async function refreshRhythms(){try{const remote=await householdApi.rhythms();if(remote.length){setRhythms(remote);localStorage.setItem("rhythms-library",JSON.stringify(remote));localStorage.setItem("rhythms-initialized","yes")}else if(!localStorage.getItem("rhythms-initialized")){await householdApi.saveRhythms(identity.id,rhythmDefaults);setRhythms(rhythmDefaults);localStorage.setItem("rhythms-initialized","yes")}}catch{}}

  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("motions")||"{}");setDone(saved.done||{});setHabits(saved.habits||[]);const library=JSON.parse(localStorage.getItem("motions-library")||"null");if(Array.isArray(library)&&library.length)setMotions(library);const rhythmLibrary=JSON.parse(localStorage.getItem("rhythms-library")||"null");if(Array.isArray(rhythmLibrary))setRhythms(rhythmLibrary)}catch{}refresh();refreshMotions();refreshRhythms();const timer=setInterval(()=>{refresh();refreshMotions();refreshRhythms()},3000);return()=>clearInterval(timer)},[day,week,rhythmPeriods.join("|")]);
  useEffect(()=>{localStorage.setItem("motions",JSON.stringify({done,habits}))},[done,habits]);
  useEffect(()=>{if(card>=motions.length)setCard(Math.max(0,motions.length-1))},[motions.length,card]);

  async function saveLibrary(next:Motion[]){setMotions(next);localStorage.setItem("motions-library",JSON.stringify(next));setSaving(true);try{await householdApi.saveMotions(identity.id,next);await refreshMotions()}catch{alert("Saved on this phone, but the shared update could not reach the household. Try again when online.")}finally{setSaving(false)}}
  function saveMotion(motion:Motion){const exists=motions.some(m=>m.id===motion.id);saveLibrary(exists?motions.map(m=>m.id===motion.id?motion:m):[...motions,motion]);setEditor(undefined);setMenuId(null)}
  function duplicateMotion(id:string){const index=motions.findIndex(m=>m.id===id);if(index<0)return;const source=motions[index],copy={...source,id:`motion-${Date.now()}`,title:`${source.title} Copy`,tasks:[...source.tasks]};const next=[...motions];next.splice(index+1,0,copy);saveLibrary(next);setMenuId(null)}
  function moveMotion(id:string,change:number){const from=motions.findIndex(m=>m.id===id),to=from+change;if(from<0||to<0||to>=motions.length)return;const next=[...motions];[next[from],next[to]]=[next[to],next[from]];saveLibrary(next);setMenuId(null)}
  function deleteMotion(id:string){const motion=motions.find(m=>m.id===id);if(!motion||!confirm(`Delete “${motion.title}”? This removes it for both Andrew and Abby.`))return;saveLibrary(motions.filter(m=>m.id!==id));if(openId===id)setOpenId(null);setMenuId(null)}
  async function saveRhythmLibrary(next:SharedRhythm[]){setRhythms(next);localStorage.setItem("rhythms-library",JSON.stringify(next));setSaving(true);try{await householdApi.saveRhythms(identity.id,next);await refreshRhythms()}catch{alert("Saved on this phone, but the shared update could not reach the household. Try again when online.")}finally{setSaving(false)}}
  function saveRhythm(rhythm:SharedRhythm){const exists=rhythms.some(r=>r.id===rhythm.id);saveRhythmLibrary(exists?rhythms.map(r=>r.id===rhythm.id?rhythm:r):[...rhythms,rhythm]);setRhythmEditor(undefined);setRhythmMenuId(null)}
  function moveRhythm(id:string,change:number){const from=rhythms.findIndex(r=>r.id===id),to=from+change;if(from<0||to<0||to>=rhythms.length)return;const next=[...rhythms];[next[from],next[to]]=[next[to],next[from]];saveRhythmLibrary(next);setRhythmMenuId(null)}
  function deleteRhythm(id:string){const rhythm=rhythms.find(r=>r.id===id);if(!rhythm||!confirm(`Delete “${rhythm.title}”? This removes it for both Andrew and Abby.`))return;saveRhythmLibrary(rhythms.filter(r=>r.id!==id));setRhythmMenuId(null)}
  function enter(m:Motion){setOpenId(m.id);setComplete(false);setFocus(false);buzz()}
  function moveCard(change:number){if(!motions.length)return;setCardMotion(change>0?"next":"prev");setCard(current=>(current+change+motions.length)%motions.length);buzz()}
  function toggle(m:Motion,t:string){const was=(done[m.id]||[]).includes(t),next=was?(done[m.id]||[]).filter(x=>x!==t):[...(done[m.id]||[]),t];setDone({...done,[m.id]:next});householdApi.setProgress(identity.id,day,"motion",`${m.id}:${m.tasks.indexOf(t)}`,!was).then(refresh).catch(()=>{});buzz(next.length===m.tasks.length);if(!was&&next.length===m.tasks.length)setTimeout(()=>setComplete(true),250)}
  function toggleRhythm(rhythm:SharedRhythm){const was=habits.includes(rhythm.id);setHabits(was?habits.filter(h=>h!==rhythm.id):[...habits,rhythm.id]);householdApi.setProgress(identity.id,rhythmPeriod(rhythm),"rhythm",rhythm.id,!was).then(refresh).catch(()=>{});buzz()}
  async function resetMotion(m:Motion){setDone(current=>({...current,[m.id]:[]}));setComplete(false);await Promise.all(m.tasks.map((_,i)=>householdApi.setProgress(identity.id,day,"motion",`${m.id}:${i}`,false).catch(()=>{})));refresh()}
  const checked=open?done[open.id]||[]:[],nextTask=open?.tasks.find(x=>!checked.includes(x));

  if(open){const index=motions.findIndex(m=>m.id===open.id);return <main className="motion" style={{"--photo":`url(${open.image})`,"--accent":open.accent} as React.CSSProperties}><div className="photo"/><div className="shade"/>{complete?<section className="complete"><i>✓</i><small>MOTION COMPLETE</small><h1>{open.message}</h1><p>Everything important has been carried forward.</p><button onClick={()=>setOpenId(null)}>RETURN TO TODAY <b>→</b></button><button className="reset-motion" onClick={()=>resetMotion(open)}>RESET THIS MOTION</button></section>:focus?<section className="focus"><header><button onClick={()=>setFocus(false)}>×</button><b>{open.title}</b><button className="more-button" onClick={()=>setMenuId(open.id)}>•••</button></header><div className="dots">{open.tasks.map(t=><i key={t} className={checked.includes(t)?"on":""}/>)}</div>{nextTask&&<><em>{String(open.tasks.indexOf(nextTask)+1).padStart(2,"0")}</em><small>UP NEXT</small><h1>{nextTask}</h1><p>{checked.length} OF {open.tasks.length} COMPLETE</p><button className="gold" onClick={()=>toggle(open,nextTask)}>✓ &nbsp; DONE</button></>}</section>:<section className="list"><header><button onClick={()=>setOpenId(null)}>×</button><button className="more-button" onClick={()=>setMenuId(open.id)}>•••</button></header><div className="title"><small>{open.label}</small><h1>{open.title}</h1><p><span>{checked.length} OF {open.tasks.length} COMPLETE</span><span>{Math.round(checked.length/Math.max(open.tasks.length,1)*100)}%</span></p><i><b style={{width:`${checked.length/Math.max(open.tasks.length,1)*100}%`}}/></i></div><div className="tasks">{open.tasks.map((t,i)=><button key={`${t}-${i}`} className={checked.includes(t)?"done":""} onClick={()=>toggle(open,t)}><i>{checked.includes(t)?"✓":""}</i><span>{t}</span><small>{String(i+1).padStart(2,"0")}</small></button>)}</div><button className="focusbtn" onClick={()=>setFocus(true)}>◎ &nbsp; ONE AT A TIME</button></section>}{menuId&&<MotionActions index={index} total={motions.length} onClose={()=>setMenuId(null)} onEdit={()=>setEditor(copyMotions([open])[0])} onDuplicate={()=>duplicateMotion(open.id)} onMove={n=>moveMotion(open.id,n)} onDelete={()=>deleteMotion(open.id)}/>} {editor!==undefined&&<MotionEditor motion={editor} onCancel={()=>setEditor(undefined)} onSave={saveMotion}/>}</main>}

  const current=motions[card];
  return <main className="app">
    {tab==="today"&&<section className="screen today"><header><div><small>{new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric"}).format(new Date()).toUpperCase()}</small><h1>MOTIONS</h1></div><button onClick={()=>setTab("house")}>{identity.name[0]}</button></header><div className="intro"><p>Your day, in order.</p><span>{motions.filter(m=>(done[m.id]||[]).length===m.tasks.length).length}/{motions.length} CLOSED</span></div>{current?<><div className="deck" onTouchStart={e=>{swiped.current=false;setTouch(e.touches[0].clientX)}} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-touch;if(Math.abs(d)>40){swiped.current=true;moveCard(d<0?1:-1);setTimeout(()=>{swiped.current=false},350)}}}><div className="back b3" style={{background:motions[(card+3)%motions.length].accent}}/><div className="back b2" style={{background:motions[(card+2)%motions.length].accent}}/><div className="back b1" style={{background:motions[(card+1)%motions.length].accent}}/><article key={current.id} className={`card-${cardMotion}`} style={{"--photo":`url(${current.image})`,"--accent":current.accent} as React.CSSProperties} onClick={()=>{if(!swiped.current)enter(current)}}><div className="cover"/><div className="fade"/><div className="top"><span>{card===0?"NEXT UP":"LATER"}</span><span>{current.time}</span></div><div className="copy"><small>{current.label}</small><h2>{current.title}</h2><p>{(done[current.id]||[]).length} OF {current.tasks.length} DONE <i><b style={{width:`${(done[current.id]||[]).length/Math.max(current.tasks.length,1)*100}%`}}/></i></p><button>OPEN MOTION <b>→</b></button></div></article></div><div className="controls"><button onClick={()=>moveCard(-1)} aria-label="Previous Motion">←</button><span>{motions.map((_,i)=><i className={i===card?"on":""} key={i}/>)}</span><button onClick={()=>moveCard(1)} aria-label="Next Motion">→</button></div><label>SWIPE THROUGH YOUR DAY</label></>:<div className="empty-motions"><h2>No Motions yet</h2><button onClick={()=>setEditor(null)}>CREATE YOUR FIRST MOTION</button></div>}</section>}
    {tab==="motions"&&<section className="screen library"><div className="library-tools"><Page title="All Motions" label="YOUR REPEATABLE LIFE"/><button onClick={()=>setEditor(null)}>＋ ADD MOTION</button></div><div className="grid">{motions.map((m,i)=><div className="motion-card-wrap" key={m.id}><button className="motion-card" onClick={()=>enter(m)} style={{"--photo":`url(${m.image})`} as React.CSSProperties}><span className="pic"/><span className="fade"/><em>{String(i+1).padStart(2,"0")}</em><div><small>{m.label}</small><b>{m.title}</b><label>{m.tasks.length} STEPS · {m.time}</label></div></button><button className="card-menu" onClick={()=>setMenuId(m.id)} aria-label={`Manage ${m.title}`}>•••</button></div>)}</div>{saving&&<div className="saving">SAVING…</div>}</section>}
    {tab==="rhythms"&&<section className="screen rhythms"><div className="rhythms-tools"><Page title="Rhythms" label="KEEP THE BEAT"/><button onClick={()=>setRhythmEditor(null)}>＋ ADD RHYTHM</button></div><h2>The habits that keep<br/>our days strong.</h2><div className="rhythm-list">{rhythms.map(r=><article className={habits.includes(r.id)?"done":""} key={r.id} role="button" tabIndex={0} onClick={()=>toggleRhythm(r)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();toggleRhythm(r)}}}><button className="rhythm-check" onClick={e=>{e.stopPropagation();toggleRhythm(r)}} aria-label={`Mark ${r.title} ${habits.includes(r.id)?"not complete":"complete"}`}>{habits.includes(r.id)?"✓":""}</button><div><small>{r.category} · {r.assignee}</small><b>{r.title}</b><label>{rhythmSchedule(r)}</label></div><button className="rhythm-menu" onClick={e=>{e.stopPropagation();setRhythmMenuId(r.id)}} aria-label={`Manage ${r.title}`}>•••</button></article>)}</div>{!rhythms.length&&<div className="empty-motions"><h2>No Rhythms yet</h2><button onClick={()=>setRhythmEditor(null)}>CREATE YOUR FIRST RHYTHM</button></div>}{saving&&<div className="saving">SAVING…</div>}</section>}
    {tab==="house"&&<section className="screen house"><Page title="Household" label="SHARED MEMORY"/><h2>We’re in this<br/>together.</h2><div className="people profile-people"><button className={identity.name==="Andrew"?"current":""} onClick={identity.name==="Andrew"?undefined:switchPerson}><i className="a"><span>A</span><img src="https://64.media.tumblr.com/0aeacc30085313da7c1bd93f61d33412/0ea49073848db7c9-3b/s540x810/576def7eac0f0da3f11d04d24a1fa676200c5727.png" alt="" onError={e=>{e.currentTarget.style.display="none"}}/></i><b>Andrew</b><small>{identity.name==="Andrew"?"THIS DEVICE":"SWITCH PROFILE"}</small></button><button className={identity.name==="Abby"?"current":""} onClick={identity.name==="Abby"?undefined:switchPerson}><i className="b"><span>A</span><img src="https://media1.popsugar-assets.com/files/thumbor/0leT8jYC1RxghEyhLWrKSMBV_k8/fit-in/728xorig/filters:format_auto-!!-:strip_icc-!!-/2016/12/12/709/n/1922564/939382c2caedb8a4_GettyImages-483778551/i/Emma-Stone-Yellow-Dress-La-La-Land.jpg" alt="" onError={e=>{e.currentTarget.style.display="none"}}/></i><b>Abby</b><small>{identity.name==="Abby"?"THIS DEVICE":"SWITCH PROFILE"}</small></button></div><div className="pulse"><small>HOUSEHOLD PULSE</small><b>{Object.values(done).flat().length+habits.length}</b><span>small things carried together today</span></div><h3>TODAY’S ACTIVITY</h3><div className="activity empty-activity">{activity.length?activity.map((r,i)=><p key={`${r.item_type}-${r.item_id}-${i}`}><b>{r.updated_by_name||"Household"}</b> completed {r.item_type==="motion"?(motions.find(m=>m.id===r.item_id.split(":")[0])?.tasks[Number(r.item_id.split(":")[1])]||"a Motion step"):r.item_type==="rhythm"?(rhythms.find(x=>x.id===r.item_id)?.title||"a Rhythm"):"an item"}</p>):<p>Activity will appear here as Andrew and Abby complete real tasks.</p>}</div><button className="switch-profile" onClick={switchPerson}>SWITCH PERSON</button></section>}
    <nav>{[["today","☼","Today"],["motions","▱","Motions"],["rhythms","≈","Rhythms"],["house","","Household"]].map(x=><button key={x[0]} className={tab===x[0]?"on":""} aria-label={x[2]} title={x[2]} onClick={()=>{setTab(x[0]);buzz()}}><i>{x[0]==="house"?<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78L12 21.23l8.84-8.84a5.5 5.5 0 0 0 0-7.78Z"/></svg>:x[1]}</i><span className="nav-label">{x[2]}</span></button>)}</nav>
    {menuId&&(()=>{const i=motions.findIndex(m=>m.id===menuId),m=motions[i];return m?<MotionActions index={i} total={motions.length} onClose={()=>setMenuId(null)} onEdit={()=>setEditor(copyMotions([m])[0])} onDuplicate={()=>duplicateMotion(m.id)} onMove={n=>moveMotion(m.id,n)} onDelete={()=>deleteMotion(m.id)}/>:null})()}
    {editor!==undefined&&<MotionEditor motion={editor} onCancel={()=>setEditor(undefined)} onSave={saveMotion}/>} 
    {rhythmMenuId&&(()=>{const i=rhythms.findIndex(r=>r.id===rhythmMenuId),r=rhythms[i];return r?<RhythmActions index={i} total={rhythms.length} onClose={()=>setRhythmMenuId(null)} onEdit={()=>setRhythmEditor({...r,days:[...r.days]})} onMove={n=>moveRhythm(r.id,n)} onDelete={()=>deleteRhythm(r.id)}/>:null})()}
    {rhythmEditor!==undefined&&<RhythmEditor rhythm={rhythmEditor} onCancel={()=>setRhythmEditor(undefined)} onSave={saveRhythm}/>} 
  </main>;
}

function Page({title,label}:{title:string;label:string}){return <header className="page"><div><small>{label}</small><h1>{title}</h1></div></header>}
export default function Home(){return <HouseholdGate>{(identity,switchPerson)=><MotionsApp identity={identity} switchPerson={switchPerson}/>}</HouseholdGate>}
