"use client";

import { useEffect, useMemo, useState } from "react";
import HouseholdGate, { Identity } from "./HouseholdGate";
import { householdApi, ProgressRow, SharedMotion } from "./supabase";

type Motion = SharedMotion;

const defaults: Motion[] = [
  {id:"morning",title:"Before 7am",label:"Morning launch",time:"Before 7:00",accent:"#d6a443",image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85",message:"Morning is moving.",tasks:["Wake up","Music ready","Play music","Things picked up for kids","Get dressed","Devotions","Eat something","Get outside as quickly as possible"]},
  {id:"church",title:"Leaving for Church",label:"Sunday departure",time:"Sunday · 9:30",accent:"#7b4b45",image:"https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&w=1200&q=85",message:"You’re ready to go.",tasks:["Make sure we have Bibles","Church attire accessories — tie, clip, shoes, bows","Hair done","Teeth brushed","Mints accessible","Supplies verified","Video ready","Van tidy","Diaper bag","Change of clothes","Energy","Pen","Prayer cards","Devices charged","Pacis","Room key","Message prepped","Route mapped","Suit coat"]},
  {id:"onway",title:"On the Way to Church",label:"Road rhythm",time:"In transit",accent:"#677457",image:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85",message:"Arrive ready.",tasks:["Route mapped","Message audio ready","Water accessible","Pray together","Arrival plan checked"]},
  {id:"leaving",title:"Leaving Church",label:"Departure sweep",time:"After service",accent:"#365d62",image:"https://images.unsplash.com/photo-1444492417251-9c84a5fa18e0?auto=format&fit=crop&w=1200&q=85",message:"Nothing left behind.",tasks:["Devices","Bibles","Table supplies","Video USB","Check","Diapers","Suit coat"]},
  {id:"dinner",title:"Dinner",label:"Evening reset",time:"Tonight",accent:"#c98258",image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85",message:"Dinner is closed.",tasks:["Clear plates and silverware","Napkins put in laundry","Dishes washed","Leftovers put away","Trash taken out","Floor swept","Table wiped down","Counters cleared of debris"]},
  {id:"bed",title:"Before Bed",label:"Night shutdown",time:"10:00 PM",accent:"#907865",image:"https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=85",message:"The house is down for the night.",tasks:["Living room picked up","Brush teeth","Wash face","Set out clothes for next day","Ironing board out of bedroom before baby","Next day game day","Devices plugged in","Lights off","Clean laundry all folded","Dirty laundry in hamper or machine","Debris organized"]}
];

const daily=["Exercise","Prayer for missionaries","Bible story prep","Bible story","Reading to kids","Watching a kids show","Drink water"];
const weekly=["Sermons uploaded","Relay log","Thank you notes","Charge watch","Polarsteps","Rocket Money / mortgage","Change in change pouch","Clean kids’ car seats","Diapers out of car"];
const buzz=(big=false)=>{if(typeof navigator!=="undefined"&&"vibrate" in navigator)navigator.vibrate(big?[25,25,45]:10)};
const dateKey=()=>{const d=new Date(),p=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const weekKey=()=>{const d=new Date(),day=(d.getDay()+6)%7,p=(n:number)=>String(n).padStart(2,"0");d.setDate(d.getDate()-day);return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const copyMotions=(items:Motion[])=>items.map(m=>({...m,tasks:[...m.tasks]}));

function MotionEditor({motion,onCancel,onSave}:{motion:Motion|null;onCancel:()=>void;onSave:(motion:Motion)=>void}){
  const [draft,setDraft]=useState<Motion>(()=>motion?{...motion,tasks:[...motion.tasks]}:{id:`motion-${Date.now()}`,title:"",label:"",time:"",image:"",accent:"#d6a443",message:"Motion complete.",tasks:[]});
  const field=(key:keyof Motion,value:string)=>setDraft({...draft,[key]:value});
  return <div className="editor-backdrop"><form className="motion-editor" onSubmit={e=>{e.preventDefault();const tasks=draft.tasks.map(task=>task.trim()).filter(Boolean);if(!draft.title.trim()||!tasks.length)return;onSave({...draft,title:draft.title.trim(),tasks})}}>
    <header><div><small>{motion?"UPDATE MOTION":"NEW MOTION"}</small><h2>{motion?"Edit Motion":"Create Motion"}</h2></div><button type="button" onClick={onCancel}>×</button></header>
    <label>Title<input value={draft.title} onChange={e=>field("title",e.target.value)} placeholder="Before 7am" required/></label>
    <div className="editor-row"><label>Small label<input value={draft.label} onChange={e=>field("label",e.target.value)} placeholder="Morning launch"/></label><label>Time<input value={draft.time} onChange={e=>field("time",e.target.value)} placeholder="Before 7:00"/></label></div>
    <label>Photo URL<input value={draft.image} onChange={e=>field("image",e.target.value)} placeholder="https://…"/></label>
    <div className="editor-row"><label>Accent color<input type="color" value={draft.accent} onChange={e=>field("accent",e.target.value)}/></label><label>Completion message<input value={draft.message} onChange={e=>field("message",e.target.value)}/></label></div>
    <label>Steps — one per line<textarea value={draft.tasks.join("\n")} onChange={e=>setDraft({...draft,tasks:e.target.value.split("\n")})} placeholder={'First step\nSecond step'} required/></label>
    <footer><button type="button" onClick={onCancel}>CANCEL</button><button className="save" type="submit">SAVE MOTION</button></footer>
  </form></div>;
}

function MotionActions({index,total,onClose,onEdit,onMove,onDelete}:{index:number;total:number;onClose:()=>void;onEdit:()=>void;onMove:(n:number)=>void;onDelete:()=>void}){
  return <div className="actions-backdrop" onClick={onClose}><div className="motion-actions" onClick={e=>e.stopPropagation()}><b>MANAGE MOTION</b><button onClick={onEdit}>Edit motion</button><button disabled={index===0} onClick={()=>onMove(-1)}>Move earlier</button><button disabled={index===total-1} onClick={()=>onMove(1)}>Move later</button><button className="danger" onClick={onDelete}>Delete motion</button><button onClick={onClose}>Cancel</button></div></div>;
}

function MotionsApp({identity,switchPerson}:{identity:Identity;switchPerson:()=>void}){
  const [tab,setTab]=useState("today"),[card,setCard]=useState(0),[openId,setOpenId]=useState<string|null>(null),[focus,setFocus]=useState(false),[done,setDone]=useState<Record<string,string[]>>({}),[habits,setHabits]=useState<string[]>([]),[activity,setActivity]=useState<ProgressRow[]>([]),[complete,setComplete]=useState(false),[touch,setTouch]=useState(0);
  const [motions,setMotions]=useState<Motion[]>(defaults),[editor,setEditor]=useState<Motion|null|undefined>(undefined),[menuId,setMenuId]=useState<string|null>(null),[saving,setSaving]=useState(false);
  const day=`day:${dateKey()}`,week=`week:${weekKey()}`;
  const open=useMemo(()=>motions.find(m=>m.id===openId)||null,[motions,openId]);

  function applyProgress(rows:ProgressRow[]){const nextDone:Record<string,string[]>={},nextHabits:string[]=[];rows.filter(r=>r.completed).forEach(r=>{if(r.item_type==="motion"){const [id,index]=r.item_id.split(":");const task=motions.find(m=>m.id===id)?.tasks[Number(index)];if(task)(nextDone[id]||=[]).push(task)}else{const item=(r.item_type==="daily"?daily:weekly)[Number(r.item_id)];if(item)nextHabits.push(item)}});setDone(nextDone);setHabits(nextHabits);setActivity(rows.filter(r=>r.completed).slice(0,12))}
  async function refresh(){try{applyProgress(await householdApi.progress([day,week]))}catch{}}
  async function refreshMotions(){try{const remote=await householdApi.motions();if(remote.length){setMotions(remote);localStorage.setItem("motions-library",JSON.stringify(remote))}}catch{}}

  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("motions")||"{}");setDone(saved.done||{});setHabits(saved.habits||[]);const library=JSON.parse(localStorage.getItem("motions-library")||"null");if(Array.isArray(library)&&library.length)setMotions(library)}catch{}refresh();refreshMotions();const timer=setInterval(()=>{refresh();refreshMotions()},3000);return()=>clearInterval(timer)},[day,week]);
  useEffect(()=>{localStorage.setItem("motions",JSON.stringify({done,habits}))},[done,habits]);
  useEffect(()=>{if(card>=motions.length)setCard(Math.max(0,motions.length-1))},[motions.length,card]);

  async function saveLibrary(next:Motion[]){setMotions(next);localStorage.setItem("motions-library",JSON.stringify(next));setSaving(true);try{await householdApi.saveMotions(identity.id,next);await refreshMotions()}catch{alert("Saved on this phone, but the shared update could not reach the household. Try again when online.")}finally{setSaving(false)}}
  function saveMotion(motion:Motion){const exists=motions.some(m=>m.id===motion.id);saveLibrary(exists?motions.map(m=>m.id===motion.id?motion:m):[...motions,motion]);setEditor(undefined);setMenuId(null)}
  function moveMotion(id:string,change:number){const from=motions.findIndex(m=>m.id===id),to=from+change;if(from<0||to<0||to>=motions.length)return;const next=[...motions];[next[from],next[to]]=[next[to],next[from]];saveLibrary(next);setMenuId(null)}
  function deleteMotion(id:string){const motion=motions.find(m=>m.id===id);if(!motion||!confirm(`Delete “${motion.title}”? This removes it for both Andrew and Abby.`))return;saveLibrary(motions.filter(m=>m.id!==id));if(openId===id)setOpenId(null);setMenuId(null)}
  function enter(m:Motion){setOpenId(m.id);setComplete(false);setFocus(false);buzz()}
  function toggle(m:Motion,t:string){const was=(done[m.id]||[]).includes(t),next=was?(done[m.id]||[]).filter(x=>x!==t):[...(done[m.id]||[]),t];setDone({...done,[m.id]:next});householdApi.setProgress(identity.id,day,"motion",`${m.id}:${m.tasks.indexOf(t)}`,!was).then(refresh).catch(()=>{});buzz(next.length===m.tasks.length);if(!was&&next.length===m.tasks.length)setTimeout(()=>setComplete(true),250)}
  function toggleHabit(x:string,type:"daily"|"weekly",index:number){const was=habits.includes(x);setHabits(was?habits.filter(h=>h!==x):[...habits,x]);householdApi.setProgress(identity.id,type==="daily"?day:week,type,String(index),!was).then(refresh).catch(()=>{});buzz()}
  async function resetMotion(m:Motion){setDone(current=>({...current,[m.id]:[]}));setComplete(false);await Promise.all(m.tasks.map((_,i)=>householdApi.setProgress(identity.id,day,"motion",`${m.id}:${i}`,false).catch(()=>{})));refresh()}
  const checked=open?done[open.id]||[]:[],nextTask=open?.tasks.find(x=>!checked.includes(x));

  if(open){const index=motions.findIndex(m=>m.id===open.id);return <main className="motion" style={{"--photo":`url(${open.image})`,"--accent":open.accent} as React.CSSProperties}><div className="photo"/><div className="shade"/>{complete?<section className="complete"><i>✓</i><small>MOTION COMPLETE</small><h1>{open.message}</h1><p>Everything important has been carried forward.</p><button onClick={()=>setOpenId(null)}>RETURN TO TODAY <b>→</b></button><button className="reset-motion" onClick={()=>resetMotion(open)}>RESET THIS MOTION</button></section>:focus?<section className="focus"><header><button onClick={()=>setFocus(false)}>×</button><b>{open.title}</b><button className="more-button" onClick={()=>setMenuId(open.id)}>•••</button></header><div className="dots">{open.tasks.map(t=><i key={t} className={checked.includes(t)?"on":""}/>)}</div>{nextTask&&<><em>{String(open.tasks.indexOf(nextTask)+1).padStart(2,"0")}</em><small>UP NEXT</small><h1>{nextTask}</h1><p>{checked.length} OF {open.tasks.length} COMPLETE</p><button className="gold" onClick={()=>toggle(open,nextTask)}>✓ &nbsp; DONE</button></>}</section>:<section className="list"><header><button onClick={()=>setOpenId(null)}>×</button><button className="more-button" onClick={()=>setMenuId(open.id)}>•••</button></header><div className="title"><small>{open.label}</small><h1>{open.title}</h1><p><span>{checked.length} OF {open.tasks.length} COMPLETE</span><span>{Math.round(checked.length/Math.max(open.tasks.length,1)*100)}%</span></p><i><b style={{width:`${checked.length/Math.max(open.tasks.length,1)*100}%`}}/></i></div><div className="tasks">{open.tasks.map((t,i)=><button key={`${t}-${i}`} className={checked.includes(t)?"done":""} onClick={()=>toggle(open,t)}><i>{checked.includes(t)?"✓":""}</i><span>{t}</span><small>{String(i+1).padStart(2,"0")}</small></button>)}</div><button className="focusbtn" onClick={()=>setFocus(true)}>◎ &nbsp; ONE AT A TIME</button></section>}{menuId&&<MotionActions index={index} total={motions.length} onClose={()=>setMenuId(null)} onEdit={()=>setEditor(copyMotions([open])[0])} onMove={n=>moveMotion(open.id,n)} onDelete={()=>deleteMotion(open.id)}/>} {editor!==undefined&&<MotionEditor motion={editor} onCancel={()=>setEditor(undefined)} onSave={saveMotion}/>}</main>}

  const current=motions[card];
  return <main className="app">
    {tab==="today"&&<section className="screen today"><header><div><small>{new Intl.DateTimeFormat(undefined,{weekday:"long",month:"long",day:"numeric"}).format(new Date()).toUpperCase()}</small><h1>MOTIONS</h1></div><button onClick={()=>setTab("house")}>{identity.name[0]}</button></header><div className="intro"><p>Your day, in order.</p><span>{motions.filter(m=>(done[m.id]||[]).length===m.tasks.length).length}/{motions.length} CLOSED</span></div>{current?<><div className="deck" onTouchStart={e=>setTouch(e.touches[0].clientX)} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-touch;if(Math.abs(d)>40){setCard((card+(d<0?1:-1)+motions.length)%motions.length);buzz()}}}><div className="back b3" style={{background:motions[(card+3)%motions.length].accent}}/><div className="back b2" style={{background:motions[(card+2)%motions.length].accent}}/><div className="back b1" style={{background:motions[(card+1)%motions.length].accent}}/><article style={{"--photo":`url(${current.image})`,"--accent":current.accent} as React.CSSProperties} onClick={()=>enter(current)}><div className="cover"/><div className="fade"/><div className="top"><span>{card===0?"NEXT UP":"LATER"}</span><span>{current.time}</span></div><div className="copy"><small>{current.label}</small><h2>{current.title}</h2><p>{(done[current.id]||[]).length} OF {current.tasks.length} DONE <i><b style={{width:`${(done[current.id]||[]).length/Math.max(current.tasks.length,1)*100}%`}}/></i></p><button>OPEN MOTION <b>→</b></button></div></article></div><div className="controls"><button onClick={()=>setCard((card-1+motions.length)%motions.length)}>←</button><span>{motions.map((_,i)=><i className={i===card?"on":""} key={i}/>)}</span><button onClick={()=>setCard((card+1)%motions.length)}>→</button></div><label>SWIPE THROUGH YOUR DAY</label></>:<div className="empty-motions"><h2>No Motions yet</h2><button onClick={()=>setEditor(null)}>CREATE YOUR FIRST MOTION</button></div>}</section>}
    {tab==="motions"&&<section className="screen library"><div className="library-tools"><Page title="All Motions" label="YOUR REPEATABLE LIFE"/><button onClick={()=>setEditor(null)}>＋ ADD MOTION</button></div><div className="grid">{motions.map((m,i)=><div className="motion-card-wrap" key={m.id}><button className="motion-card" onClick={()=>enter(m)} style={{"--photo":`url(${m.image})`} as React.CSSProperties}><span className="pic"/><span className="fade"/><em>{String(i+1).padStart(2,"0")}</em><div><small>{m.label}</small><b>{m.title}</b><label>{m.tasks.length} STEPS · {m.time}</label></div></button><button className="card-menu" onClick={()=>setMenuId(m.id)} aria-label={`Manage ${m.title}`}>•••</button></div>)}</div>{saving&&<div className="saving">SAVING…</div>}</section>}
    {tab==="rhythms"&&<section className="screen rhythms"><Page title="Rhythms" label="KEEP THE BEAT"/><h2>The habits that keep<br/>our days strong.</h2><h3>DAILY RHYTHMS</h3><div className="habitgrid">{daily.map((x,i)=><button key={x} className={habits.includes(x)?"done":""} onClick={()=>toggleHabit(x,"daily",i)}><i>{habits.includes(x)?"✓":["↟","✦","◫","⌁","◌","◉","≈"][i]}</i><b>{x}</b><small>{habits.includes(x)?"DONE":"TAP TO MARK"}</small></button>)}</div><h3>THIS WEEK</h3><div className="week">{weekly.map((x,i)=><button key={x} className={habits.includes(x)?"done":""} onClick={()=>toggleHabit(x,"weekly",i)}><i>{habits.includes(x)?"✓":"○"}</i><span>{x}</span><small>WEEKLY</small></button>)}</div></section>}
    {tab==="house"&&<section className="screen house"><Page title="Household" label="SHARED MEMORY"/><h2>We’re in this<br/>together.</h2><div className="people profile-people"><button className={identity.name==="Andrew"?"current":""} onClick={identity.name==="Andrew"?undefined:switchPerson}><i className="a">A</i><b>Andrew</b><small>{identity.name==="Andrew"?"THIS DEVICE":"SWITCH PROFILE"}</small></button><button className={identity.name==="Abby"?"current":""} onClick={identity.name==="Abby"?undefined:switchPerson}><i className="b">A</i><b>Abby</b><small>{identity.name==="Abby"?"THIS DEVICE":"SWITCH PROFILE"}</small></button></div><div className="pulse"><small>HOUSEHOLD PULSE</small><b>{Object.values(done).flat().length+habits.length}</b><span>small things carried together today</span></div><h3>TODAY’S ACTIVITY</h3><div className="activity empty-activity">{activity.length?activity.map((r,i)=><p key={`${r.item_type}-${r.item_id}-${i}`}><b>{r.updated_by_name||"Household"}</b> completed {r.item_type==="motion"?(motions.find(m=>m.id===r.item_id.split(":")[0])?.tasks[Number(r.item_id.split(":")[1])]||"a Motion step"):(r.item_type==="daily"?daily:weekly)[Number(r.item_id)]}</p>):<p>Activity will appear here as Andrew and Abby complete real tasks.</p>}</div><button className="switch-profile" onClick={switchPerson}>SWITCH PERSON</button></section>}
    <nav>{[["today","☼","Today"],["motions","▱","Motions"],["rhythms","≈","Rhythms"],["house","♧","Household"]].map(x=><button key={x[0]} className={tab===x[0]?"on":""} onClick={()=>{setTab(x[0]);buzz()}}><i>{x[1]}</i><span>{x[2]}</span></button>)}</nav>
    {menuId&&(()=>{const i=motions.findIndex(m=>m.id===menuId),m=motions[i];return m?<MotionActions index={i} total={motions.length} onClose={()=>setMenuId(null)} onEdit={()=>setEditor(copyMotions([m])[0])} onMove={n=>moveMotion(m.id,n)} onDelete={()=>deleteMotion(m.id)}/>:null})()}
    {editor!==undefined&&<MotionEditor motion={editor} onCancel={()=>setEditor(undefined)} onSave={saveMotion}/>} 
  </main>;
}

function Page({title,label}:{title:string;label:string}){return <header className="page"><div><small>{label}</small><h1>{title}</h1></div></header>}
export default function Home(){return <HouseholdGate>{(identity,switchPerson)=><MotionsApp identity={identity} switchPerson={switchPerson}/>}</HouseholdGate>}
